project:
  type: website

website:
  title: "Jerin's Personal Blog"
  site-url: https://jerin248486.github.io/personal_blog/
  twitter-card:
    creator: "@UMassDACSS"
    site: "@UMassDACSS"
  favicon: images/DACSS_Round_Network.png
  navbar:
    background: "#881c1c"
    logo: images/Jerin_image/headshot_jerin.jpg
    right:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - href: https://umass.edu/sbs/dacss
        text: "Resume"
      - text: "Projects"
        href: https://dacss.github.io/DACSS_601_August2022_v2
      - text: "Contact"
        href: https://dacss.github.io/DACSS_601_August2022_v2
      - icon: github
        href: https://github.com/DACSS/DACSS_601_August2022_v2
        aria-label: GitHub
      

execution:
  freeze: auto


format:
  html:
    mainfont: Open Sans
    linkcolor: "#881c1c"
    toc: true
    theme: 
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
