---
title: "My Resume"
desription: "This is the most updated resume of Jerin Jacob"
#date: "11/08/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
editor: 
  markdown: 
    wrap: 72
---

```{r}
#| label: setup
#| warning: false

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```

# **JERIN JACOB**

Worcester, MA\|857-746-1136\| jerin248486\@gmail.com \| LinkedIn

## **EDUCATION**

**Master of Science in Data Analytics and Computational Social Science**
\| AUG 2022- EXPECTED DEC 2023 \| University of Massachusetts, Amherst,
MA Relevant Coursework: Introduction to Data Science, Research Design,
Public Opinion in Politics

**MBA (Marketing)** \| MAY 2011 University of Kerala\|CGPA: 6.9 Relevant
Coursework: Marketing Management, Business Communication, Advertising &
Sales Promotion, Brand Management

**Bachelor of Science in Physics** \| MAR 2008 Mahatma Gandhi University
\| CCPA: 6.3

## **PROFESSIONAL EXPERIENCE**

**Career Ambassador** \| Data Analytics and Computational Social
Science, Amherst, MA SEP 2022- PRESENT \| Manage and promote LinkedIn
Page, Curate Handshake content for the biweekly newsletter, Develop and
deploy student surveys, Manage the 'Minute Fund' and 'UMass Gives'
fundraising efforts for DACSS program at University of Massachusetts,
Amherst.

**Business Consultant\|Freelance** MAR 2020- JUL 2022 Helped the clients
to build and execute a marketing strategy for monthly, quarterly, and
annual plans to achieve a 35% increase in the annual revenue growth.
Designed and implemented a brand management program for clients to
increase brand recognition and brand loyalty.

**Managing Director** \| Eazyshopy by Cresoul Trading & Logistics Pvt
Ltd, INDIA NOV 2014-DEC 2019 Headed the business development and
operations of the startup to achieve more than 80% annual growth in
revenue in 4 consecutive years Developed the brand identities and
created a strong brand consciousness among the target population Built
and improved the infrastructure and resources for the startup Headed the
recruitment and HR development Identified new market channels and
executed the market penetration Strategic Consulting, including business
plan & sales strategy development.

**Marketing Specialist** \|Eastern Hazar, Saudi Arabia OCT 2012-OCT 2014
Developed Marketing materials and updated at regular intervals Managed
the social media accounts and communities Developed and executed the
digital marketing campaigns for the company Constantly interacted with
the shop floor managers and the technical team to make sure the customer
gets delighted Headed the sales and marketing for the Eastern province,
Saudi Arabia

**Marketing Manager** \|Sookshmatech Integral Techno Solutions Pvt Ltd,
India MAY 2011-APR 2012 Key responsibilities included Ad making, Media
Management, Social Media Marketing, Prepare Marketing Collaterals,
Market Research, Identifying Target Customers, Sales Presentation &
Closing the deal

**Assistant Store Manager** \|PJ Electronics & Home Appliance shop,
India JUN 2008-MAY 2009 Assisted in day-to-day operations of the store
and actively participated in the merchandising

## **DOMAIN SKILLS**
 
**Programming Languages:** 
R, SQL, Python, HTML & CSS 

**Reporting and Analytical tools:** 
R, Advanced MS Excel, Tableau

**Soft Skills:** 
Communication skills, Adaptability, Attention to detail, Time Management, Negotiation Skill.

## **RELEVANT PROJECTS**

Study on the effect of embedded marketing in movies of regional language
in Kerala, India FEB-MAR 2011 The research was conducted on the
effectiveness of embedded marketing and the results. Respondents from
multiple demographic groups were surveyed and some of the industry
people were interviewed to do the study. The responses of the
questionnaire were statistically analyzed and resulted in a positive
correlation to the brand recollection but no direct dependence of
improvement of sales was observed.

## **ACHIEVEMENTS**

Worked in the organizing team of multiple inter-collegiate events \|
2009-2011 Chaired as the Joint Secretary, Core Executive Committee for
MBA department \| 2010-2011 Chaired the position of Secretary, KCYM at
the parish for one year \| 2006 - 2007
